ifndef::website[]
= rink(5)
:manmanual: Rink Manual
:mansource: Rink Manual

Name
----
rink - TOML configuration file format.
endif::[]

Description
-----------
Rink's configuration file uses the TOML format.

Duration types accept common suffixes like `ms`, `s`, `h`, `d`, `y`.
Size types accept suffixes like `MB`.

Color strings are a set of keywords separated by spaces. The following
keywords are understood:

*black*, *red*, *green*, *yellow*, *blue*, *purple*, *cyan*, *white*::
*dark_gray*, *light_red*, *light_green*, *light_yellow*, *light_blue*, *light_purple*, *magenta*, *light_magenta*, *light_cyan*, *light_gray*::
    Sets the color to that ANSI color.
*dim*/*dimmed*::
	Uses a dimmed variant of the color instead of the bright variant.
*bold*, *italic*, *underline*/*under*, *strikethrough*::
	Formatting.
*hidden*/*none*::
	Makes the text invisible.
*on*::
	The color keyword after this will apply to the background instead of
	the foreground. Example: `black on red`.
*default*/*plain*::
	Results in unstyled text.
integers 0 to 255::
	Extended terminal color palette codes.
*#* <__6 hex letters__>::
	Hex codes can be used to specify truecolor.
	Example: `#000000`
*rgb(* <__red__> *,* <__green__> *,* <__blue__> *)*::
	RGB values can be used to specify truecolor. No spaces are allowed.
	Example: `rgb(10,10,10)`

Rink
~~~~
The `[rink]` section.

*prompt* = <__string__>::
	The text that will be displayed before the cursor, to hint
	interactivity. Should include the space character.
	Default: `"> "`

*long_output* = <__bool__>::
	Breaks lists, such as search results, over multiple lines. Requires
	a Unicode-capable terminal.
	Default: `false`

Currency
~~~~~~~~
The `[currency]` section.

*enabled* = <__bool__>::
	Currency support can be disabled entirely. When set to false, the
	`currency.json` will not be loaded, and trying to use currency units
	will give a "not found" error.
	Default: `true`

*behavior* = <__"prompt"__ | __"always"__>::
	Default: `"prompt"`. When attempting to use a currency unit, Rink will
	ask if you'd like to download the currency data.
+
Seting it to `"always"` will download immediately when a currency unit
is used.

*cache_expiration_enabled* = <__bool__>::
	Default: `true`. Setting this to `false` causes rink to behave as if
	`cache_duration` was infinite. If the currency file doesn't exist, it
	will fetch it, otherwise it will use it indefinitely. Rink can be
	invoked with `--fetch-currency` to download the latest version.
+
This setting might be useful for intermittent internet access. You can
setup a cron job to fetch the currency data while the network is up,
making it available later when using rink offline.

*endpoint* = <__url__>::
	Allows pointing to alternate Rink-Web instances, or to any other API
	that offers a compatible format.
	Default: `"https://rinkcalc.app/data/currency.json"`

*timeout* = <__duration__>::
	How long to wait for currency fetching before giving up.
	Default: `"15s"`

*cache_duration* = <__duration__>::
	How long to wait before considering the cached currency data stale.
	Default: `"1h"`

Colors
~~~~~~
The `[colors]` section.

*enabled* = <__bool__>::
	Set to true to turn on colored output.
	Default: `true`, or `false` if the `NO_COLOR` environment variable is set.

*theme* = <__string__>::
	Sets the active theme. See the THEMES section.
	Default: `"default"`

Themes
~~~~~~
The `[themes]` section. This section is a dictionary, each theme should be
created as `[themes.my_theme]`. These options are specific to each.

*plain* = <__color__>::
	Generic text. This will be used often.
	Default: `"default"`

*error* = <__color__>::
	Error messages.
	Default: `"red"`

*unit* = <__color__>::
	The names of units, like `kilogram`.
	Default: `"cyan"`

*quantity* = <__color__>::
	The names of physical quantities, like `length` and `time`. These
	are shown in parentheses on every query.
	Default: `"dimmed cyan"`

*number* = <__color__>::
	Numbers that appear in outputs.
	Default: `"default"`

*user_input* = <__color__>::
	Used when rink is quoting user input back, such as in unit not found
	errors.
	Default: `"bold"`

*doc_string* = <__color__>::
	Used when rink is showing informational text that's part of the
	definition of a unit, like `meter`.
	Default: `"italic"`

*pow* = <__color__>::
	The `^2` in `m/s^2`.
	Default: `"default"`

*prop_name* = <__color__>::
	Names of properties in substances, like the `speed` in `speed of
	light`.
	Default: `"cyan"`

*date_time* = <__color__>::
	Date time objects, that can be obtained with the hash notation or
	`now`.
	Default: `"default"`

*link* = <__color__>::
	A hyperlink, typically found inside of doc strings.
	Default: `"cyan"`

Files
-----
Linux::
	++__$XDG_CONFIG_DIR__/rink/config.toml++

Windows::
	++__{FOLDERID_RoamingAppData}__\rink\config.toml++

macOS::
	++__$HOME__/Library/Application Support/rink/config.toml++

ifndef::website[]
See also
--------
xref:rink.1.adoc[rink(1)], xref:rink.7.adoc[rink(7)],
xref:rink-defs.5.adoc[rink-defs(5)],
xref:rink-dates.5.adoc[rink-dates(5)]
endif::[]
